version: '3.7'

services:
    reddit-discord-bot:
        image: ghcr.io/topisenpai/anicord
        container_name: anicord-bot
        restart: unless-stopped
        volumes:
            - ./config.yml:/var/lib/anicord.yml
        ports:
            - 80:80
